name: Docker CI

# on:
#  push:
#    branches: [ "dev" ]
#  pull_request:
#    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Backend Jar with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: bootJar
        build-root-directory: ETSystem
    - name: Build Docker Images
      run: docker compose build
      working-directory: "./docker/"
    - name: Save Frontend Image
      run: docker save --output frontend-image.tar docker-frontend
      working-directory: "./docker/"
    - name: Save Backend Image
      run: docker save --output backend-image.tar docker-backend
      working-directory: "./docker/"
    - name: Upload Images
      uses: actions/upload-artifact@v4
      with:
        name: images
        path: "./docker/*-image.tar"