name: Docker CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::992382812807:role/gh-actions-worker
        aws-region: eu-west-2
    - name: Build Backend Jar with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: bootJar
        build-root-directory: ETSystem
    - name: Build & Tag Docker Images
      run: |
        docker compose build
        docker tag docker-frontend 992382812807.dkr.ecr.eu-west-2.amazonaws.com/ets-frontend:latest
        docker tag docker-backend 992382812807.dkr.ecr.eu-west-2.amazonaws.com/ets-backend:latest
      working-directory: "./docker/"
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Push Images to ECR
      run: |
        docker push 992382812807.dkr.ecr.eu-west-2.amazonaws.com/ets-frontend:latest
        docker push 992382812807.dkr.ecr.eu-west-2.amazonaws.com/ets-backend:latest